name: sifakapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  go_router: 13.2.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.3
  flutter_timezone: ^4.1.1
  crypto: ^3.0.3
  permission_handler: ^11.3.1
  awesome_notifications: ^0.10.1
  workmanager: ^0.9.0+3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.5.4
  hive_generator: 2.0.1
  go_router_builder: 2.8.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/medications/medication_list.json
    - assets/data/medications/medication_categories.json

